import { Quote } from "../types";

export const mockQuotes: Quote[] = [
  {
    id: "1",
    quoteNo: "QU-590480",
    date: "2025-06-01",
    customer: "Mayfords Estate Agents",
    siteDelivery: "Flat 19, 2, Havanna Drive, London NW11 9BB",
    noQuotes: "1",
    total: 500,
    email: "propertymanagement@mayfords.com",
    description: "Plumbing & Electrical Installations and Replacements",
  },
  {
    id: "2",
    quoteNo: "QU-590481",
    date: "2025-06-02",
    customer: "Acme Corp",
    siteDelivery: "123 Tech Street, London NW10 1AB",
    noQuotes: "1",
    total: 1200,
    email: "support@acme.com",
    description: "Office Electrical Upgrades",
  },
  {
    id: "3",
    quoteNo: "Q-1003",
    date: "2025-06-03",
    customer: "Jane Smith",
    siteDelivery: "12 Baker St, London W1U 3BZ",
    noQuotes: "1",
    total: 750,
    email: "jane.smith@email.com",
    description: "Bathroom renovation",
  },
  {
    id: "4",
    quoteNo: "Q-1004",
    date: "2025-06-04",
    customer: "XYZ Ltd.",
    siteDelivery: "456 Commerce Rd, London E2 8AA",
    noQuotes: "1",
    total: 300,
    email: "info@xyz.com",
    description: "Lighting installation",
  },
  {
    id: "5",
    quoteNo: "Q-1005",
    date: "2025-06-05",
    customer: "Globex Inc.",
    siteDelivery: "78 Industrial Park, London SW15 3FF",
    noQuotes: "1",
    total: 950,
    email: "contact@globex.com",
    description: "Electrical system upgrade",
  },
  {
    id: "6",
    quoteNo: "Q-1006",
    date: "2025-06-01",
    customer: "John Doe",
    siteDelivery: "10 Elm Street, London NW1 5DJ",
    noQuotes: "1",
    total: 5000,
    email: "john.doe@email.com",
    description: "Full house rewiring",
  },
  {
    id: "7",
    quoteNo: "Q-1007",
    date: "2025-06-02",
    customer: "Acme Corp",
    siteDelivery: "123 Tech Street, London NW10 1AB",
    noQuotes: "1",
    total: 100,
    email: "support@acme.com",
    description: "Minor repairs",
  },
  {
    id: "8",
    quoteNo: "Q-1008",
    date: "2025-06-03",
    customer: "Jane Smith",
    siteDelivery: "12 Baker St, London W1U 3BZ",
    noQuotes: "1",
    total: 0,
    email: "jane.smith@email.com",
    description: "Consultation only",
  },
  {
    id: "9",
    quoteNo: "Q-1009",
    date: "2025-06-04",
    customer: "XYZ Ltd.",
    siteDelivery: "456 Commerce Rd, London E2 8AA",
    noQuotes: "1",
    total: 3000,
    email: "info@xyz.com",
    description: "Server room setup",
  },
  {
    id: "10",
    quoteNo: "Q-10010",
    date: "2025-06-05",
    customer: "Globex Inc.",
    siteDelivery: "78 Industrial Park, London SW15 3FF",
    noQuotes: "1",
    total: 95,
    email: "contact@globex.com",
    description: "Light switch replacement",
  },
  {
    id: "11",
    quoteNo: "Q-10011",
    date: "2025-06-06",
    customer: "FutureTech",
    siteDelivery: "1 Innovation Way, London E1 6AN",
    noQuotes: "1",
    total: 1800,
    email: "info@futuretech.com",
    description: "Smart home installation",
  },
  {
    id: "12",
    quoteNo: "Q-10012",
    date: "2025-06-07",
    customer: "GreenFields",
    siteDelivery: "33 Eco St, London N5 1LL",
    noQuotes: "1",
    total: 120,
    email: "contact@greenfields.org",
    description: "Garden lighting",
  },
  {
    id: "13",
    quoteNo: "Q-10013",
    date: "2025-06-08",
    customer: "TechWizards",
    siteDelivery: "9 Wizard Lane, London W2 4QQ",
    noQuotes: "1",
    total: 670,
    email: "support@techwizards.io",
    description: "Network installation",
  },
  {
    id: "14",
    quoteNo: "Q-10014",
    date: "2025-06-09",
    customer: "BrightHome",
    siteDelivery: "14 Light Avenue, London N10 2PA",
    noQuotes: "1",
    total: 850,
    email: "sales@brighthome.co.uk",
    description: "Lighting upgrade",
  },
  {
    id: "15",
    quoteNo: "Q-10015",
    date: "2025-06-10",
    customer: "UrbanBuild",
    siteDelivery: "22 Builder St, London E14 3AE",
    noQuotes: "1",
    total: 1400,
    email: "project@urbanbuild.com",
    description: "Office electrical planning",
  },
  {
    id: "16",
    quoteNo: "Q-10016",
    date: "2025-06-11",
    customer: "SafeHouse",
    siteDelivery: "77 Secure Rd, London SW3 6TT",
    noQuotes: "1",
    total: 230,
    email: "admin@safehouse.net",
    description: "Alarm system installation",
  },
  {
    id: "17",
    quoteNo: "Q-10017",
    date: "2025-06-12",
    customer: "NeoDesigns",
    siteDelivery: "6 Modern St, London EC1A 7AA",
    noQuotes: "1",
    total: 990,
    email: "design@neodesigns.com",
    description: "Studio wiring",
  },
  {
    id: "18",
    quoteNo: "Q-10018",
    date: "2025-06-13",
    customer: "CookCo",
    siteDelivery: "55 Kitchen Rd, London NW6 5PD",
    noQuotes: "1",
    total: 410,
    email: "orders@cookco.uk",
    description: "Appliance electrical fitting",
  },
  {
    id: "19",
    quoteNo: "Q-10019",
    date: "2025-06-14",
    customer: "BuildSmart",
    siteDelivery: "88 Smart Lane, London E17 9PL",
    noQuotes: "1",
    total: 2450,
    email: "support@buildsmart.com",
    description: "Commercial building fit-out",
  },
  {
    id: "20",
    quoteNo: "Q-10020",
    date: "2025-06-15",
    customer: "FixItNow",
    siteDelivery: "3 Handy Court, London SE1 2TH",
    noQuotes: "1",
    total: 330,
    email: "fix@fixitnow.io",
    description: "Emergency repair",
  },
  {
    id: "21",
    quoteNo: "Q-10021",
    date: "2025-06-16",
    customer: "MegaBuild",
    siteDelivery: "101 Tower Street, London E3 2LH",
    noQuotes: "1",
    total: 3800,
    email: "info@megabuild.com",
    description: "High-rise electrical setup",
  },
  {
    id: "22",
    quoteNo: "Q-10022",
    date: "2025-06-17",
    customer: "RapidRepair",
    siteDelivery: "12 Fast Lane, London SW7 1BJ",
    noQuotes: "1",
    total: 275,
    email: "repairs@rapidrepair.uk",
    description: "Fuse box repair",
  },
  {
    id: "23",
    quoteNo: "Q-10023",
    date: "2025-06-18",
    customer: "NextGen Systems",
    siteDelivery: "78 Future Park, London EC2A 4NA",
    noQuotes: "1",
    total: 1450,
    email: "nextgen@systems.co",
    description: "Smart system integration",
  },
  {
    id: "24",
    quoteNo: "Q-10024",
    date: "2025-06-19",
    customer: "InteriorX",
    siteDelivery: "67 Style Blvd, London N11 3EF",
    noQuotes: "1",
    total: 820,
    email: "contact@interiorx.com",
    description: "Interior lighting overhaul",
  },
  {
    id: "25",
    quoteNo: "Q-10025",
    date: "2025-06-20",
    customer: "Eventus",
    siteDelivery: "15 Concert Ave, London SE11 4HB",
    noQuotes: "1",
    total: 1320,
    email: "events@eventus.co.uk",
    description: "Event venue wiring",
  },
  {
    id: "26",
    quoteNo: "Q-10026",
    date: "2025-06-21",
    customer: "LightWave",
    siteDelivery: "202 Glow Street, London NW9 0LP",
    noQuotes: "1",
    total: 2750,
    email: "sales@lightwave.com",
    description: "LED system installation",
  },
  {
    id: "27",
    quoteNo: "Q-10027",
    date: "2025-06-22",
    customer: "BuildRight",
    siteDelivery: "34 Hammer Ln, London E15 1JD",
    noQuotes: "1",
    total: 900,
    email: "team@buildright.org",
    description: "Domestic rewiring",
  },
  {
    id: "28",
    quoteNo: "Q-10028",
    date: "2025-06-23",
    customer: "SparkFlow",
    siteDelivery: "66 Riverbank St, London W4 3DD",
    noQuotes: "1",
    total: 1100,
    email: "connect@sparkflow.io",
    description: "Loft conversion electrical",
  },
  {
    id: "29",
    quoteNo: "Q-10029",
    date: "2025-06-24",
    customer: "ElectroFix",
    siteDelivery: "9 Fixer Yard, London SW12 9PN",
    noQuotes: "1",
    total: 470,
    email: "bookings@electrofix.com",
    description: "Ceiling fan installation",
  },
  {
    id: "30",
    quoteNo: "Q-10030",
    date: "2025-06-25",
    customer: "WiredUp",
    siteDelivery: "41 Grid Close, London EC4R 3TR",
    noQuotes: "1",
    total: 670,
    email: "hello@wiredup.uk",
    description: "Warehouse lighting setup",
  },
  {
    id: "31",
    quoteNo: "Q-10031",
    date: "2025-06-26",
    customer: "EcoWatt",
    siteDelivery: "5 Solar Rise, London N8 0JJ",
    noQuotes: "1",
    total: 1950,
    email: "service@ecowatt.com",
    description: "Solar panel system wiring",
  },
  {
    id: "32",
    quoteNo: "Q-10032",
    date: "2025-06-27",
    customer: "PowerSecure",
    siteDelivery: "99 Voltage Rd, London SE2 1XX",
    noQuotes: "1",
    total: 1225,
    email: "support@powersecure.io",
    description: "Backup generator install",
  },
  {
    id: "33",
    quoteNo: "Q-10033",
    date: "2025-06-28",
    customer: "SmartPlug Ltd",
    siteDelivery: "47 Socket Way, London W5 2BA",
    noQuotes: "1",
    total: 330,
    email: "admin@smartplug.co.uk",
    description: "Smart plug setup",
  },
  {
    id: "34",
    quoteNo: "Q-10034",
    date: "2025-06-29",
    customer: "AlphaWorks",
    siteDelivery: "17 Alpha Street, London E9 6LL",
    noQuotes: "1",
    total: 2875,
    email: "projects@alphaworks.com",
    description: "Factory power distribution",
  },
  {
    id: "35",
    quoteNo: "Q-10035",
    date: "2025-06-30",
    customer: "LuxLiving",
    siteDelivery: "3 Elegant Rd, London SW4 4PS",
    noQuotes: "1",
    total: 750,
    email: "lux@livinglux.com",
    description: "Luxury apartment lighting",
  },
  {
    id: "36",
    quoteNo: "Q-10036",
    date: "2025-07-01",
    customer: "DigitalSpace",
    siteDelivery: "100 Pixel Pl, London EC3M 7EB",
    noQuotes: "1",
    total: 1420,
    email: "connect@digitalspace.io",
    description: "Server rack and wiring",
  },
  {
    id: "37",
    quoteNo: "Q-10037",
    date: "2025-07-02",
    customer: "Fix&Go",
    siteDelivery: "77 Quick Ln, London N1 6AT",
    noQuotes: "1",
    total: 320,
    email: "jobs@fixandgo.uk",
    description: "Electrical troubleshooting",
  },
  {
    id: "38",
    quoteNo: "Q-10038",
    date: "2025-07-03",
    customer: "NeoHomes",
    siteDelivery: "21 Future Crescent, London NW2 3SD",
    noQuotes: "1",
    total: 1160,
    email: "info@neohomes.co.uk",
    description: "New home wiring plan",
  },
  {
    id: "39",
    quoteNo: "Q-10039",
    date: "2025-07-04",
    customer: "BrightLabs",
    siteDelivery: "19 Lab Lane, London W6 7PP",
    noQuotes: "1",
    total: 2100,
    email: "labs@brightlabs.com",
    description: "Laboratory power setup",
  },
  {
    id: "40",
    quoteNo: "Q-10040",
    date: "2025-07-05",
    customer: "SwitchMasters",
    siteDelivery: "82 Toggle Dr, London SE15 2ZX",
    noQuotes: "1",
    total: 410,
    email: "contact@switchmasters.com",
    description: "Switchboard installation",
  },
  {
    id: "41",
    quoteNo: "Q-10041",
    date: "2025-07-06",
    customer: "HomeCircuit",
    siteDelivery: "14 Fuse Lane, London W11 3AA",
    noQuotes: "1",
    total: 980,
    email: "hello@homecircuit.co.uk",
    description: "Fuse box upgrade",
  },
  {
    id: "42",
    quoteNo: "Q-10042",
    date: "2025-07-07",
    customer: "LightLogic",
    siteDelivery: "33 Illumination Rd, London E14 9PT",
    noQuotes: "1",
    total: 1340,
    email: "support@lightlogic.com",
    description: "Smart lighting system install",
  },
  {
    id: "43",
    quoteNo: "Q-10043",
    date: "2025-07-08",
    customer: "PowerLine Ltd.",
    siteDelivery: "9 Current Dr, London NW3 5QQ",
    noQuotes: "1",
    total: 720,
    email: "info@powerline.co.uk",
    description: "Socket rewiring",
  },
  {
    id: "44",
    quoteNo: "Q-10044",
    date: "2025-07-09",
    customer: "VoltGen",
    siteDelivery: "28 Circuit Court, London SW1A 1AA",
    noQuotes: "1",
    total: 2450,
    email: "volts@voltgen.io",
    description: "Industrial generator install",
  },
  {
    id: "45",
    quoteNo: "Q-10045",
    date: "2025-07-10",
    customer: "ClearCharge",
    siteDelivery: "66 Energy Ave, London N7 7TT",
    noQuotes: "1",
    total: 860,
    email: "contact@clearcharge.com",
    description: "EV charger setup",
  },
  {
    id: "46",
    quoteNo: "Q-10046",
    date: "2025-07-11",
    customer: "NovaElectrics",
    siteDelivery: "12 Quantum Rd, London W1G 8PY",
    noQuotes: "1",
    total: 1770,
    email: "projects@novaelectrics.uk",
    description: "Complete office wiring",
  },
  {
    id: "47",
    quoteNo: "Q-10047",
    date: "2025-07-12",
    customer: "SmartNest",
    siteDelivery: "45 IoT Lane, London EC1M 4AJ",
    noQuotes: "1",
    total: 980,
    email: "iot@smartnest.com",
    description: "Home automation setup",
  },
  {
    id: "48",
    quoteNo: "Q-10048",
    date: "2025-07-13",
    customer: "CoreElectric",
    siteDelivery: "88 Ampere St, London N4 1BX",
    noQuotes: "1",
    total: 1495,
    email: "admin@coreelectric.uk",
    description: "Data center installation",
  },
  {
    id: "49",
    quoteNo: "Q-10049",
    date: "2025-07-14",
    customer: "UrbanWatt",
    siteDelivery: "71 Grid Rd, London SE10 0XY",
    noQuotes: "1",
    total: 680,
    email: "service@urbanwatt.io",
    description: "Warehouse wiring",
  },
  {
    id: "50",
    quoteNo: "Q-10050",
    date: "2025-07-15",
    customer: "AmpZone",
    siteDelivery: "23 Voltage View, London W9 1JH",
    noQuotes: "1",
    total: 310,
    email: "help@ampzone.com",
    description: "Outlet repairs",
  },
  {
    id: "51",
    quoteNo: "Q-10051",
    date: "2025-07-16",
    customer: "MegaWatts Ltd.",
    siteDelivery: "11 Dynamo Drive, London EC2A 4NA",
    noQuotes: "1",
    total: 2890,
    email: "info@megawatts.uk",
    description: "High voltage system setup",
  },
  {
    id: "52",
    quoteNo: "Q-10052",
    date: "2025-07-17",
    customer: "WiredUp",
    siteDelivery: "64 Cable Way, London SE1 9GF",
    noQuotes: "1",
    total: 910,
    email: "support@wiredup.co.uk",
    description: "Rewiring small office",
  },
  {
    id: "53",
    quoteNo: "Q-10053",
    date: "2025-07-18",
    customer: "BrightFuture Homes",
    siteDelivery: "18 Sunshine Lane, London N15 4QT",
    noQuotes: "1",
    total: 1470,
    email: "hello@brightfuture.com",
    description: "Lighting and solar integration",
  },
  {
    id: "54",
    quoteNo: "Q-10054",
    date: "2025-07-19",
    customer: "Pulse Electric",
    siteDelivery: "10 Beat St, London W10 6JP",
    noQuotes: "1",
    total: 530,
    email: "projects@pulseelectric.com",
    description: "Appliance installation",
  },
  {
    id: "55",
    quoteNo: "Q-10055",
    date: "2025-07-20",
    customer: "GridSmart",
    siteDelivery: "95 Net Road, London SW8 3EE",
    noQuotes: "1",
    total: 1920,
    email: "info@gridsmart.io",
    description: "Smart meter and grid linkup",
  },
  {
    id: "56",
    quoteNo: "Q-10056",
    date: "2025-07-21",
    customer: "SafeCircuit",
    siteDelivery: "22 Fuse Park, London NW4 9GA",
    noQuotes: "1",
    total: 810,
    email: "contact@safecircuit.uk",
    description: "Safety inspection and repair",
  },
  {
    id: "57",
    quoteNo: "Q-10057",
    date: "2025-07-22",
    customer: "ElectroForce",
    siteDelivery: "6 Powerfield Rd, London E3 5HF",
    noQuotes: "1",
    total: 2300,
    email: "jobs@electroforce.co.uk",
    description: "Warehouse power grid overhaul",
  },
  {
    id: "58",
    quoteNo: "Q-10058",
    date: "2025-07-23",
    customer: "Litehouse Ltd.",
    siteDelivery: "40 Bright Ave, London E8 1NH",
    noQuotes: "1",
    total: 1190,
    email: "lite@litehouse.uk",
    description: "LED system for new offices",
  },
  {
    id: "59",
    quoteNo: "Q-10059",
    date: "2025-07-24",
    customer: "Voltify",
    siteDelivery: "29 Charge Row, London SW9 8DP",
    noQuotes: "1",
    total: 720,
    email: "support@voltify.com",
    description: "Electrical car charger install",
  },
  {
    id: "60",
    quoteNo: "Q-10060",
    date: "2025-07-25",
    customer: "Amptronics",
    siteDelivery: "81 Electron Rd, London NW6 2ES",
    noQuotes: "1",
    total: 1380,
    email: "contact@amptronics.io",
    description: "Industrial machinery connection",
  },
  {
    id: "61",
    quoteNo: "Q-10061",
    date: "2025-07-26",
    customer: "PowerNest",
    siteDelivery: "55 Gridlock St, London N1 0PS",
    noQuotes: "1",
    total: 1570,
    email: "projects@powernest.io",
    description: "Server room cabling",
  },
  {
    id: "62",
    quoteNo: "Q-10062",
    date: "2025-07-27",
    customer: "Watt & Co.",
    siteDelivery: "12 Watt Street, London SE10 9LS",
    noQuotes: "1",
    total: 850,
    email: "hello@wattco.com",
    description: "Light system retrofit",
  },
  {
    id: "63",
    quoteNo: "Q-10063",
    date: "2025-07-28",
    customer: "GlowTech",
    siteDelivery: "77 Neon Blvd, London W8 5JJ",
    noQuotes: "1",
    total: 1950,
    email: "contact@glowtech.uk",
    description: "Building-wide lighting automation",
  },
  {
    id: "64",
    quoteNo: "Q-10064",
    date: "2025-07-29",
    customer: "EnergyLink",
    siteDelivery: "34 Connector Lane, London SW1P 2AN",
    noQuotes: "1",
    total: 1030,
    email: "support@energylink.io",
    description: "Energy monitoring system install",
  },
  {
    id: "65",
    quoteNo: "Q-10065",
    date: "2025-07-30",
    customer: "PulseFlow Ltd.",
    siteDelivery: "50 Rhythm Rd, London EC1V 7PB",
    noQuotes: "1",
    total: 610,
    email: "admin@pulseflow.com",
    description: "Lighting maintenance",
  },
  {
    id: "66",
    quoteNo: "Q-10066",
    date: "2025-07-31",
    customer: "ZapCore",
    siteDelivery: "19 Volt Crescent, London NW3 4NG",
    noQuotes: "1",
    total: 2010,
    email: "zap@zapcore.uk",
    description: "EV fleet charging stations",
  },
  {
    id: "67",
    quoteNo: "Q-10067",
    date: "2025-08-01",
    customer: "LightCraft",
    siteDelivery: "5 Beam Way, London SE15 6DN",
    noQuotes: "1",
    total: 925,
    email: "service@lightcraft.co.uk",
    description: "Track lighting setup",
  },
  {
    id: "68",
    quoteNo: "Q-10068",
    date: "2025-08-02",
    customer: "ElectraSpace",
    siteDelivery: "90 Orbit St, London W1T 3JY",
    noQuotes: "1",
    total: 1765,
    email: "connect@electraspace.io",
    description: "Power for co-working hub",
  },
  {
    id: "69",
    quoteNo: "Q-10069",
    date: "2025-08-03",
    customer: "LiveWire Solutions",
    siteDelivery: "22 Current Path, London N19 3DA",
    noQuotes: "1",
    total: 845,
    email: "team@livewire.solutions",
    description: "Emergency repair service",
  },
  {
    id: "70",
    quoteNo: "Q-10070",
    date: "2025-08-04",
    customer: "NeoWatts Ltd.",
    siteDelivery: "8 Pulse Park, London SE8 4LL",
    noQuotes: "1",
    total: 1430,
    email: "neo@neowatts.co.uk",
    description: "Modern office fit-out",
  },
  {
    id: "71",
    quoteNo: "Q-10071",
    date: "2025-08-05",
    customer: "BrightBox Ltd.",
    siteDelivery: "14 Circuit Ave, London NW5 2LE",
    noQuotes: "1",
    total: 1120,
    email: "info@brightbox.uk",
    description: "Storage unit wiring",
  },
  {
    id: "72",
    quoteNo: "Q-10072",
    date: "2025-08-06",
    customer: "ChargePoint Systems",
    siteDelivery: "33 Battery Ln, London SE13 7XT",
    noQuotes: "1",
    total: 1780,
    email: "service@chargepoint.io",
    description: "Electric vehicle infrastructure",
  },
  {
    id: "73",
    quoteNo: "Q-10073",
    date: "2025-08-07",
    customer: "EcoLight",
    siteDelivery: "21 Green St, London E17 9HB",
    noQuotes: "1",
    total: 960,
    email: "eco@ecolight.co.uk",
    description: "Low-energy lighting upgrade",
  },
  {
    id: "74",
    quoteNo: "Q-10074",
    date: "2025-08-08",
    customer: "PowerGrid Solutions",
    siteDelivery: "9 Voltage Rd, London N8 0QH",
    noQuotes: "1",
    total: 2550,
    email: "support@powergrid.solutions",
    description: "Data center UPS setup",
  },
  {
    id: "75",
    quoteNo: "Q-10075",
    date: "2025-08-09",
    customer: "Watson Electric",
    siteDelivery: "76 Baker Dr, London EC4A 2BQ",
    noQuotes: "1",
    total: 740,
    email: "hello@watsonelectric.uk",
    description: "Old house rewiring",
  },
  {
    id: "76",
    quoteNo: "Q-10076",
    date: "2025-08-10",
    customer: "SkyVolt Ltd.",
    siteDelivery: "12 Cloud Rd, London W14 0DD",
    noQuotes: "1",
    total: 1980,
    email: "team@skyvolt.uk",
    description: "Smart home electrical systems",
  },
  {
    id: "77",
    quoteNo: "Q-10077",
    date: "2025-08-11",
    customer: "Electronix Co.",
    siteDelivery: "100 Ohm Ln, London SE5 9JL",
    noQuotes: "1",
    total: 870,
    email: "info@electronix.co.uk",
    description: "CCTV and security wiring",
  },
  {
    id: "78",
    quoteNo: "Q-10078",
    date: "2025-08-12",
    customer: "WattLab",
    siteDelivery: "5 Lab St, London N7 6BH",
    noQuotes: "1",
    total: 1510,
    email: "support@wattlab.io",
    description: "Lab equipment power network",
  },
  {
    id: "79",
    quoteNo: "Q-10079",
    date: "2025-08-13",
    customer: "GlowHub",
    siteDelivery: "40 Beam Sq, London E14 6RT",
    noQuotes: "1",
    total: 620,
    email: "contact@glowhub.uk",
    description: "Office lighting maintenance",
  },
  {
    id: "80",
    quoteNo: "Q-10080",
    date: "2025-08-14",
    customer: "ZapLabs",
    siteDelivery: "61 Amp Way, London N16 8JQ",
    noQuotes: "1",
    total: 990,
    email: "lab@zaplabs.com",
    description: "Prototype test lab setup",
  },
  {
    id: "81",
    quoteNo: "Q-10081",
    date: "2025-08-15",
    customer: "WiredWorks",
    siteDelivery: "22 Cable Ct, London NW6 4ER",
    noQuotes: "1",
    total: 870,
    email: "info@wiredworks.uk",
    description: "Factory automation wiring",
  },
  {
    id: "82",
    quoteNo: "Q-10082",
    date: "2025-08-16",
    customer: "NeoCurrent",
    siteDelivery: "11 Spark Rd, London SE10 9XL",
    noQuotes: "1",
    total: 1340,
    email: "hello@neocurrent.io",
    description: "Retail unit electrical upgrade",
  },
  {
    id: "83",
    quoteNo: "Q-10083",
    date: "2025-08-17",
    customer: "ElectroServe",
    siteDelivery: "31 Terminal Dr, London W1D 3QA",
    noQuotes: "1",
    total: 720,
    email: "support@electroserve.com",
    description: "Emergency call-out",
  },
  {
    id: "84",
    quoteNo: "Q-10084",
    date: "2025-08-18",
    customer: "PowerNet Systems",
    siteDelivery: "59 Grid Ave, London E8 1HQ",
    noQuotes: "1",
    total: 2100,
    email: "contact@powernet.uk",
    description: "Enterprise server wiring",
  },
  {
    id: "85",
    quoteNo: "Q-10085",
    date: "2025-08-19",
    customer: "HomeTech UK",
    siteDelivery: "8 Smart Ln, London SW6 3ZZ",
    noQuotes: "1",
    total: 690,
    email: "info@hometech.co.uk",
    description: "Smart light installation",
  },
  {
    id: "86",
    quoteNo: "Q-10086",
    date: "2025-08-20",
    customer: "PulseVolt",
    siteDelivery: "45 Surge St, London N1 0EY",
    noQuotes: "1",
    total: 1820,
    email: "team@pulsevolt.io",
    description: "Control panel replacement",
  },
  {
    id: "87",
    quoteNo: "Q-10087",
    date: "2025-08-21",
    customer: "FixIt Electrics",
    siteDelivery: "3 Repair Way, London EC3M 4AB",
    noQuotes: "1",
    total: 400,
    email: "fix@fixitelectrics.com",
    description: "Socket and switch fix",
  },
  {
    id: "88",
    quoteNo: "Q-10088",
    date: "2025-08-22",
    customer: "BrightPath",
    siteDelivery: "17 Shine Rd, London NW3 7HP",
    noQuotes: "1",
    total: 990,
    email: "service@brightpath.uk",
    description: "Garden lighting system",
  },
  {
    id: "89",
    quoteNo: "Q-10089",
    date: "2025-08-23",
    customer: "NovaGrid",
    siteDelivery: "66 Sparkle St, London SE15 5HZ",
    noQuotes: "1",
    total: 1440,
    email: "info@novagrid.com",
    description: "Warehouse electrics",
  },
  {
    id: "90",
    quoteNo: "Q-10090",
    date: "2025-08-24",
    customer: "VoltEdge",
    siteDelivery: "28 Power Cres, London W6 8EZ",
    noQuotes: "1",
    total: 1250,
    email: "sales@voltedge.io",
    description: "Electrical consultation",
  },
  {
    id: "91",
    quoteNo: "Q-10091",
    date: "2025-08-25",
    customer: "GridTech",
    siteDelivery: "9 Energy Ln, London N19 3TR",
    noQuotes: "1",
    total: 1370,
    email: "contact@gridtech.co.uk",
    description: "Backup generator installation",
  },
  {
    id: "92",
    quoteNo: "Q-10092",
    date: "2025-08-26",
    customer: "WattZone",
    siteDelivery: "53 Circuit Way, London SE8 4HH",
    noQuotes: "1",
    total: 980,
    email: "hello@wattzone.uk",
    description: "Office energy optimization",
  },
  {
    id: "93",
    quoteNo: "Q-10093",
    date: "2025-08-27",
    customer: "LuxLight Ltd.",
    siteDelivery: "12 Glow Ct, London W5 4UZ",
    noQuotes: "1",
    total: 1450,
    email: "info@luxlight.uk",
    description: "Hallway LED installation",
  },
  {
    id: "94",
    quoteNo: "Q-10094",
    date: "2025-08-28",
    customer: "ElectraBuild",
    siteDelivery: "84 Current Rd, London E11 3AT",
    noQuotes: "1",
    total: 2100,
    email: "support@electrabuild.io",
    description: "New building electrical layout",
  },
  {
    id: "95",
    quoteNo: "Q-10095",
    date: "2025-08-29",
    customer: "SafeConnect",
    siteDelivery: "7 Shield Ave, London SW3 2JD",
    noQuotes: "1",
    total: 640,
    email: "info@safeconnect.uk",
    description: "Fuse board upgrade",
  },
  {
    id: "96",
    quoteNo: "Q-10096",
    date: "2025-08-30",
    customer: "SmartPower",
    siteDelivery: "39 AI Dr, London NW8 9BP",
    noQuotes: "1",
    total: 1880,
    email: "ai@smartpower.com",
    description: "Intelligent power control system",
  },
  {
    id: "97",
    quoteNo: "Q-10097",
    date: "2025-08-31",
    customer: "SparkLine",
    siteDelivery: "21 Wire Row, London SE4 1ND",
    noQuotes: "1",
    total: 720,
    email: "help@sparkline.co.uk",
    description: "Electrical diagnostics",
  },
  {
    id: "98",
    quoteNo: "Q-10098",
    date: "2025-09-01",
    customer: "CoreVolt",
    siteDelivery: "61 Core St, London EC2M 6DF",
    noQuotes: "1",
    total: 1150,
    email: "service@corevolt.uk",
    description: "Industrial control systems",
  },
  {
    id: "99",
    quoteNo: "Q-10099",
    date: "2025-09-02",
    customer: "AmpX Ltd.",
    siteDelivery: "19 Boost Dr, London N2 0EL",
    noQuotes: "1",
    total: 1345,
    email: "support@ampx.io",
    description: "Commercial lighting retrofit",
  },
  {
    id: "100",
    quoteNo: "Q-10100",
    date: "2025-09-03",
    customer: "Volticity",
    siteDelivery: "3 Tesla Ct, London W10 5JJ",
    noQuotes: "1",
    total: 2990,
    email: "team@volticity.uk",
    description: "Complete electrical renovation",
  },
];
